'use client';

import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type Language = 'en' | 'zh';

const zh = {
  'language.switchToChinese': '切换为中文',
  'language.switchToEnglish': '切换为英文',
  'navigation.dashboard': '仪表盘',
  'navigation.newJob': '新建任务',
  'navigation.queue': '任务队列',
  'navigation.datasets': '数据集',
  'navigation.settings': '设置',
  'navigation.openMenu': '打开菜单',
  'navigation.closeMenu': '关闭菜单',
  'navigation.support': '支持 AI-Toolkit',
  'theme.light': '切换为浅色模式',
  'theme.dark': '切换为深色模式',
  'dashboard.title': '仪表盘',
  'dashboard.queues': '任务队列',
  'dashboard.viewAll': '查看全部',
  'dashboard.gpuMonitor': 'GPU 监控',
  'dashboard.lastUpdated': '最后更新：{time}',
  'queue.title': '任务队列',
  'queue.newJob': '+ 新建',
  'queue.newTrainingJob': '新建训练任务',
  'datasets.title': '数据集',
  'datasets.new': '+ 新建',
  'datasets.newDataset': '新建数据集',
  'datasets.name': '数据集名称',
  'datasets.actions': '操作',
  'datasets.deleteTitle': '删除数据集',
  'datasets.deleteMessage': '确定要删除数据集“{name}”吗？此操作无法撤销。',
  'datasets.enterName': '请输入新数据集的名称：',
  'datasets.nameRequired': '必须填写数据集名称。',
  'settings.title': '设置',
  'settings.hfToken': 'Hugging Face 令牌',
  'settings.hfHelp': '如需访问受限或私有模型，请创建一个只读令牌：',
  'settings.hfPlaceholder': '输入 Hugging Face 令牌',
  'settings.trainingPath': '训练文件夹路径',
  'settings.trainingHelp': '训练信息将保存在此处。必须使用绝对路径；留空时默认使用项目根目录的 output 文件夹。',
  'settings.trainingPlaceholder': '输入训练文件夹路径',
  'settings.datasetPath': '数据集文件夹路径',
  'settings.datasetHelp': '用于存放和查找数据集。',
  'settings.datasetWarning': '警告：软件可能会修改数据集，建议另行备份或为本软件使用专用文件夹。',
  'settings.datasetPlaceholder': '输入数据集文件夹路径',
  'settings.saving': '正在保存…',
  'settings.save': '保存设置',
  'settings.saved': '设置已保存。',
  'settings.error': '保存设置失败，请重试。',
  'common.actions': '操作',
  'common.cancel': '取消',
  'common.confirm': '确认',
  'common.create': '创建',
  'common.delete': '删除',
  'common.refresh': '刷新',
  'common.empty': '暂无数据',
  'common.loading': '加载中…',
  'jobs.name': '名称',
  'jobs.steps': '步数',
  'jobs.status': '状态',
  'jobs.info': '信息',
  'jobs.idle': '空闲',
  'jobs.running': '运行中',
  'jobs.stopped': '已停止',
  'jobs.start': '启动',
  'jobs.stop': '停止',
  'jobs.clear': '清除',
  'jobs.deleteSelected': '删除所选任务',
  'jobs.selected': '已选择 {count} 个任务',
  'jobs.deleting': '正在删除 {done} / {total}…',
  'jobs.deleteTitle': '删除任务',
  'jobs.deleteMessage': '确定要删除 {count} 个任务吗？这些任务也将从磁盘上永久移除。',
  'jobs.status.queued': '排队中',
  'jobs.status.running': '运行中',
  'jobs.status.stopping': '正在停止',
  'jobs.status.completed': '已完成',
  'jobs.status.failed': '已失败',
  'gpu.temperature': '温度',
  'gpu.fanSpeed': '风扇转速',
  'gpu.load': 'GPU 负载',
  'gpu.memory': '显存',
  'gpu.clockSpeed': '时钟频率',
  'gpu.powerDraw': '功耗',
  'gpu.noData': '暂无 GPU 数据。',
  'gpu.noNvidia': '未检测到 NVIDIA GPU！',
  'gpu.noNvidiaHelp': '此系统上无法使用 nvidia-smi。',
  'gpu.noneFound': '未找到 GPU，但 nvidia-smi 可用。',
  'gpu.error': '错误！',
  'auth.password': '密码',
  'auth.placeholder': '输入密码',
  'auth.help': '密码由环境变量 AI_TOOLKIT_AUTH 设置，默认值为“password”。',
  'auth.checking': '验证中…',
  'auth.check': '验证密码',
  'auth.invalid': '密码无效，请重试。',
  'auth.required': '请输入密码。',
  'newJob.title': '新建训练任务',
  'newJob.editTitle': '编辑训练任务',
  'newJob.import': '导入配置',
  'newJob.simple': '简单',
  'newJob.advanced': '高级',
  'newJob.showSimple': '显示简单配置',
  'newJob.showAdvanced': '显示高级配置',
  'newJob.saving': '正在保存…',
  'newJob.update': '更新',
  'newJob.create': '创建',
  'newJob.updateJob': '更新任务',
  'newJob.createJob': '创建任务',
  'newJob.advancedDetected': '检测到高级任务，请切换到高级视图继续。',
} as const;

export type TranslationKey = keyof typeof zh;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey, variables?: Record<string, string | number>) => string;
  translate: (text: string) => string;
};

// Translations for labels supplied by configuration-driven and reusable form
// components. Keeping these here lets newer upstream fields fall back to their
// English label without breaking the page, while known labels remain localized.
const rawZh: Record<string, string> = {
  Job: '任务',
  Model: '模型',
  'Quantize / Compile': '量化 / 编译',
  Target: '目标',
  Save: '保存',
  Training: '训练',
  Advanced: '高级',
  Datasets: '数据集',
  Sample: '采样',
  Settings: '设置',
  Options: '选项',
  Multistage: '多阶段',
  Slider: '滑条',
  'Training Name': '训练名称',
  'Enter training name': '请输入训练名称',
  'GPU ID': 'GPU 编号',
  'Trigger Word': '触发词',
  'Model Architecture': '模型架构',
  'Name or Path': '名称或路径',
  'Training Adapter Path': '训练适配器路径',
  'Unconditional Adapter Path': '无条件适配器路径',
  'Low VRAM': '低显存',
  'Match Target Res': '匹配目标分辨率',
  'Layer Offloading': '分层卸载',
  'Transformer Offload %': 'Transformer 卸载百分比',
  'Text Encoder Offload %': '文本编码器卸载百分比',
  Transformer: 'Transformer',
  'Text Encoder': '文本编码器',
  'Compile Options': '编译选项',
  'Compile Model': '编译模型',
  'Stages to Train': '训练阶段',
  'High Noise': '高噪声',
  'Low Noise': '低噪声',
  'Switch Every': '切换间隔（步）',
  'Target Type': '目标类型',
  'LoKr Factor': 'LoKr 因子',
  'Linear Rank': '线性秩',
  'Conv Rank': '卷积秩',
  'Target Class': '目标类别',
  'Positive Prompt': '正向提示词',
  'Negative Prompt': '负向提示词',
  'Anchor Class': '锚点类别',
  'Data Type': '数据类型',
  'Save Every': '保存间隔（步）',
  'Max Step Saves to Keep': '最多保留的分步存档数',
  'Batch Size': '批大小',
  'Gradient Accumulation': '梯度累积',
  Steps: '总步数',
  Optimizer: '优化器',
  'Learning Rate': '学习率',
  'Weight Decay': '权重衰减',
  'Timestep Type': '时间步类型',
  'Timestep Bias': '时间步偏置',
  'Loss Type': '损失类型',
  'Audio Loss Multiplier': '音频损失倍率',
  'EMA (Exponential Moving Average)': 'EMA（指数移动平均）',
  'Use EMA': '启用 EMA',
  'EMA Decay': 'EMA 衰减率',
  'Text Encoder Optimizations': '文本编码器优化',
  'Unload TE': '卸载文本编码器',
  'Unload Text Encoder': '卸载文本编码器',
  'Cache Text Embeddings': '缓存文本嵌入',
  Regularization: '正则化',
  'Differential Output Preservation': '差异化输出保持',
  'DOP Loss Multiplier': 'DOP 损失倍率',
  'DOP Preservation Class': 'DOP 保持类别',
  'Blank Prompt Preservation': '空提示词保持',
  'BPP Loss Multiplier': 'BPP 损失倍率',
  'Do Differential Guidance': '启用差分引导',
  'Differential Guidance': '差分引导',
  'Differential Guidance Scale': '差分引导强度',
  'Duplicate Dataset': '复制数据集',
  'Remove Dataset': '删除数据集',
  'Target Dataset': '目标数据集',
  'Control Dataset': '控制数据集',
  'Control Dataset 1': '控制数据集 1',
  'Control Dataset 2': '控制数据集 2',
  'Control Dataset 3': '控制数据集 3',
  'Multi Control Dataset': '多控制数据集',
  'LoRA Weight': 'LoRA 权重',
  'Num Repeats': '重复次数',
  'Default Caption': '默认描述',
  'Caption Dropout Rate': '描述丢弃率',
  'Caption Extension': '描述文件扩展名',
  'Num Frames': '帧数',
  'Number of Frames': '帧数',
  'Cache Latents': '缓存潜变量',
  'Is Regularization': '用作正则化',
  'Auto Frame Count': '自动帧数',
  'Do I2V': '启用图生视频',
  'Do Audio': '启用音频',
  'Audio Normalize': '音频标准化',
  'Audio Preserve Pitch': '保持音高',
  Flipping: '翻转',
  'Flip X': '水平翻转',
  'Flip Y': '垂直翻转',
  Resolutions: '分辨率',
  'Sample Every': '采样间隔（步）',
  Sampler: '采样器',
  'Guidance Scale': '引导强度',
  'Sample Steps': '采样步数',
  Width: '宽度',
  Height: '高度',
  FPS: '帧率',
  Seed: '随机种子',
  'Walk Seed': '种子递增',
  'Advanced Sampling': '高级采样',
  'Skip First Sample': '跳过首次采样',
  'Force First Sample': '强制首次采样',
  'Disable Sampling': '禁用采样',
  Prompt: '提示词',
  'Enter prompt': '请输入提示词',
  'LoRA Scale': 'LoRA 强度',
  'Control Images': '控制图',
  'Add Control Image': '添加控制图',
  Dataset: '数据集',
  'Add Dataset': '添加数据集',
  'Upsample Prompts': '扩写提示词',
  'Edit caption & boxes': '编辑描述和边界框',
  'Add Prompt': '添加提示词',
  'Training saved successfully!': '训练任务保存成功！',
  'Error saving training. Please try again.': '保存训练任务失败，请重试。',
  'Loading...': '加载中…',
  Delete: '删除',
  Download: '下载',
  'Delete Sample': '删除采样',
  'Are you sure you want to delete this sample? This action cannot be undone.':
    '确定要删除这张采样图吗？此操作无法撤销。',
  'Hide bounding boxes': '隐藏边界框',
  'Show bounding boxes': '显示边界框',
  'Confirm Action': '确认操作',
  Close: '关闭',
  'Click or drop': '点击或拖拽上传',
  Replace: '替换',
  'Uploading…': '上传中…',
  'Uploading...': '上传中…',
  video: '视频',
  image: '图片',
  'Are you sure you want to delete this video? This action cannot be undone.': '确定要删除这个视频吗？此操作无法撤销。',
  'Are you sure you want to delete this image? This action cannot be undone.': '确定要删除这张图片吗？此操作无法撤销。',
  'Loading caption...': '正在加载描述…',
  'Drop the image here...': '松开以上传…',
  'Drag & drop an image here, or click to select one': '拖拽图片到这里，或点击选择',
  Cancel: '取消',
  'Add Images to:': '添加文件到：',
  'Drag & drop files here or click to select': '拖拽文件到这里，或点击选择',
  'Images, videos, .txt or .json supported': '支持图片、视频、音频、.txt 和 .json',
  'Drop more files to add to queue': '继续拖拽文件可追加到上传队列',
  'Cancel Upload': '取消上传',
  'Delete Checkpoint': '删除模型文件',
  'Are you sure you want to delete this checkpoint? This action cannot be undone.':
    '确定要删除这个模型文件吗？此操作无法撤销。',
  Checkpoints: '模型文件',
  merge: '融合',
  'Error loading checkpoints': '模型文件加载失败',
  'No checkpoints available': '暂无模型文件',
  'Loading Images': '正在加载图片',
  'Please wait while we fetch your dataset images...': '请稍候，正在获取数据集图片…',
  'Error Loading Images': '加载图片失败',
  'There was a problem fetching the images. Please try refreshing the page.': '获取图片时出现问题，请刷新页面后重试。',
  'No Images Found': '未找到图片',
  'This dataset is empty. Click "Add Images" to get started.': '该数据集为空，请点击“添加图片”开始。',
  Add: '添加',
  'Add Images': '添加图片',
  Captioning: '打标任务',
  'Error fetching job': '获取任务失败',
  Overview: '概览',
  Samples: '样例',
  'Loss Graph': '损失曲线',
  'Config File': '配置文件',
  Plugin: '插件',
  Progress: '进度',
  Step: '第',
  'Job Name': '任务名称',
  'Assigned GPUs': '分配的 GPU',
  Speed: '速度',
  'Loading log...': '正在加载日志…',
  'Error loading log': '加载日志失败',
  'Stop Job': '停止任务',
  'Are you sure you want to stop this job? You can resume it later.': '确定要停止此任务吗？稍后可以恢复。',
  Stop: '停止',
  'Delete Job': '删除任务',
  'Are you sure you want to delete this job? It will also be permanently removed from disk.':
    '确定要删除此任务吗？任务文件也会从磁盘永久删除。',
  'WARNING: The job is currently running. You should stop it first if you can.':
    '警告：任务仍在运行，请尽可能先停止任务。',
  'Clone Job': '克隆任务',
  'Save Next Step': '下一步保存',
  'Mark stopped warning':
    '确定要强制将此任务标记为已停止吗？这只会修正卡住的状态，并不会停止实际运行中的任务。请仅在确认任务已经停止时执行。',
  'Mark Job as Stopped': '强制标记为已停止',
  'Mark as Stopped': '标记为已停止',
  'Loss graph': '损失图表',
  'Refreshing...': '刷新中…',
  Error: '错误',
  steps: '步',
  'No data yet': '暂无数据',
  Refresh: '刷新',
  'Failed to load loss logs.': '加载损失日志失败。',
  'Waiting for loss points...': '等待损失数据…',
  Display: '显示设置',
  Trend: '趋势线',
  'Log Y': '对数坐标',
  'Clip outliers': '去除异常值',
  Series: '数据系列',
  'No loss keys found yet.': '暂无损失数据系列。',
  Smoothing: '平滑度',
  'Plot stride': '绘图步长',
  every: '每',
  pt: '点',
  'UI downsample for huge runs.': '用于超大训练记录的界面降采样。',
  'Dataset path is missing. Please try again.': '数据集路径缺失，请重试。',
  'A caption job for this dataset already exists. Please check your jobs list.':
    '该数据集的打标任务已存在，请到任务列表中查看。',
  'Failed to save job. Please try again.': '保存任务失败，请重试。',
  'Caption Dataset': '数据集打标',
  Simple: '简单',
  'Add to Queue': '加入队列',
  'Auto Captioning...': '正在自动打标…',
  'Auto Caption': '自动打标',
  Caption: '打标',
  'Captioner Type': '打标器类型',
  'Name or Path 2': '名称或路径 2',
  'Fixed Caption': '固定描述',
  'Enter fixed caption (if you want the same caption for all audio files)': '如果所有音频文件使用相同描述，请在此输入',
  Quantize: '量化',
  'Max Resolution': '最大分辨率',
  'Max New Tokens': '最大新 Token 数',
  Recaption: '重新打标',
  'Compile Models': '编译模型',
  'Caption Prompt': '打标提示词',
  'Enter caption prompt': '请输入打标提示词',
  'Script timed out.': '脚本执行超时。',
  'Script exited with code': '脚本退出，退出码',
  'Unknown error': '未知错误',
  'Merge LoRAs': '融合 LoRA',
  'Merging LoRAs... please do not close this window.': '正在融合 LoRA，请不要关闭此窗口。',
  'Merge failed. See log below.': '融合失败，请查看下方日志。',
  'Merge complete.': '融合完成。',
  'Starting...': '正在启动…',
  'Output Filename': '输出文件名',
  'Enter output filename': '请输入输出文件名',
  'Add LoRA': '添加 LoRA',
  'Selected LoRAs': '已选择的 LoRA',
  Remove: '移除',
  Merge: '开始融合',
  'Upsample GPU warning':
    '此操作会加载模型并占用 GPU。建议至少预留 13GB 空闲显存；开始前请确认 GPU 空闲，否则可能因显存不足而失败。',
  'Upsampling... please do not close this window.': '正在扩写，请不要关闭此窗口。',
  'Finished with errors. See log below.': '扩写已结束，但存在错误，请查看下方日志。',
  'Upsampling complete.': '提示词扩写完成。',
  'Select prompts to upsample': '选择要扩写为 Ideogram 结构化描述的提示词。已选择',
  'Select all': '全选',
  None: '全不选',
  Creative: '创意模式',
  On: '开启',
  Off: '关闭',
  'Expands the idea — places the subject in a scene and adds fitting details.':
    '扩展原始想法，将主体置于合适场景并补充细节。',
  'Faithful — structures the prompt as given, with a minimal background.': '忠实整理原提示词结构，只补充最少的背景。',
  'Additional instructions (optional)': '附加说明（可选）',
  'e.g. keep it a close-up portrait, prefer a daytime setting, always include a 9:16 vertical framing...':
    '例如：保持近景人像、优先白天场景、始终采用 9:16 竖构图…',
  upsampled: '已扩写',
  'Upsampling...': '正在扩写…',
  Upsample: '扩写',
  'Show & edit bounding boxes': '显示并编辑边界框',
  'Edit Prompt': '编辑提示词',
  'Enter prompt...': '请输入提示词…',
  'Convert to structured caption': '转换为结构化描述',
  Saved: '已保存',
  'Close modal': '关闭弹窗',
  'Clear image': '清除图片',
  'Delete checkpoint': '删除模型文件',
  'Delete optimizer state': '删除优化器状态',
  'Scroll to Top': '滚动到顶部',
  'Scroll to Bottom': '滚动到底部',
  Medium: '媒介',
  'Custom…': '自定义…',
  'custom medium': '自定义媒介',
  'Pick color': '选择颜色',
  'Remove color': '移除颜色',
  'Ideogram Caption': 'Ideogram 结构化描述',
  'Unsaved changes': '有未保存的更改',
  'High-level description': '整体描述',
  'One-sentence summary of the image...': '用一句话概括图片…',
  Style: '风格',
  Aesthetics: '美学风格',
  Lighting: '光照',
  'Photo (camera / film)': '摄影（相机 / 胶片）',
  'Art style (rendering technique)': '艺术风格（渲染技法）',
  '35mm film still, shallow depth of field': '35mm 胶片画面，浅景深',
  'flat vector, clean edges': '扁平矢量，边缘简洁',
  'Color palette (max 16)': '调色板（最多 16 种）',
  Background: '背景',
  'The scene shell: walls, floor, sky, ambient light...': '场景环境：墙面、地面、天空、环境光…',
  Elements: '元素',
  'Add element': '添加元素',
  'Draw a new box on the image': '在图片上绘制新边界框',
  'Drawing… (esc to cancel)': '正在绘制…（按 Esc 取消）',
  'Draw box': '绘制边界框',
  'Select (highlights its box on the image)': '选择（在图片中高亮边界框）',
  'Delete element': '删除元素',
  'Text (rendered in image)': '文字（图片中呈现）',
  Description: '描述',
  'Bounding box': '边界框',
  '(none)': '（无）',
  remove: '移除',
  'add box': '添加边界框',
  'Colors (max 5)': '颜色（最多 5 种）',
  'Hide raw JSON': '隐藏原始 JSON',
  'Raw JSON': '原始 JSON',
  Audio: '音频',
  Restart: '重新播放',
  Pause: '暂停',
  Play: '播放',
  'Buffering…': '缓冲中…',
  Scrub: '拖动定位',
  instruction: '指令编辑',
  experimental: '实验性',
  audio: '音频',
  Standard: '标准',
  'Accuracy Recovery Adapters': '精度恢复适配器',
  'Additional Quantization Options': '其他量化选项',
  Auto: '自动',
  Linear: '线性',
  Shift: '偏移',
  Weighted: '加权',
  'Mean Absolute Error': '平均绝对误差',
  Wavelet: '小波损失',
  'Stepped Recovery': '分步恢复',
  '- NONE -': '- 不量化 -',
  'Delete Image': '删除图片',
  File: '文件',
  'Templates...': '模板…',
  'Add a caption...': '添加描述…',
  'CPU Info': 'CPU 信息',
  'No CPU data available': '暂无 CPU 数据',
  'CPU Load': 'CPU 负载',
  Memory: '内存',
  'Loading plugin...': '正在加载插件…',
  'Error loading plugin': '加载插件失败',
  Custom: '自定义',
  'Enter custom value': '请输入自定义值',
  'float8 (default)': 'float8（默认）',
  '512 (default)': '512（默认）',
  '128 (default)': '128（默认）',
  Balanced: '均衡',
  Sigmoid: 'Sigmoid',
  'Mean Squared Error': '均方误差',
};

function translateRaw(text: string): string {
  const exact = rawZh[text];
  if (exact) return exact;
  if (/^eg\.\s*/i.test(text)) return text.replace(/^eg\.\s*/i, '例如：');
  if (text.endsWith(' (default)')) return `${text.slice(0, -10)}（默认）`;
  const controlImage = text.match(/^Add Control Image (\d+)$/);
  if (controlImage) return `添加控制图 ${controlImage[1]}`;
  const prompt = text.match(/^Prompt #(\d+)$/);
  if (prompt) return `提示词 #${prompt[1]}`;
  if (text.startsWith('Enter ')) return `请输入${rawZh[text.slice(6)] ?? text.slice(6)}`;
  return text;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const stored = localStorage.getItem('language');
    const initial: Language =
      stored === 'zh' || stored === 'en' ? stored : navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en';
    setLanguageState(initial);
    document.documentElement.lang = initial === 'zh' ? 'zh-CN' : 'en';
  }, []);

  const setLanguage = (next: Language) => {
    setLanguageState(next);
    localStorage.setItem('language', next);
    document.documentElement.lang = next === 'zh' ? 'zh-CN' : 'en';
  };

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage(language === 'en' ? 'zh' : 'en'),
      translate: text => (language === 'zh' && typeof text === 'string' ? translateRaw(text) : text),
      t: (key, variables) => {
        let text: string = language === 'zh' ? zh[key] : key;
        if (language === 'en') {
          const english = {
            'language.switchToChinese': 'Switch to Chinese',
            'language.switchToEnglish': 'Switch to English',
            'navigation.dashboard': 'Dashboard',
            'navigation.newJob': 'New Job',
            'navigation.queue': 'Queue',
            'navigation.datasets': 'Datasets',
            'navigation.settings': 'Settings',
            'navigation.openMenu': 'Open menu',
            'navigation.closeMenu': 'Close menu',
            'navigation.support': 'Support AI-Toolkit',
            'theme.light': 'Switch to light mode',
            'theme.dark': 'Switch to dark mode',
            'dashboard.title': 'Dashboard',
            'dashboard.queues': 'Queues',
            'dashboard.viewAll': 'View All',
            'dashboard.gpuMonitor': 'GPU Monitor',
            'dashboard.lastUpdated': 'Last updated: {time}',
            'queue.title': 'Queue',
            'queue.newJob': '+ New Job',
            'queue.newTrainingJob': 'New Training Job',
            'datasets.title': 'Datasets',
            'datasets.new': '+ New',
            'datasets.newDataset': 'New Dataset',
            'datasets.name': 'Dataset Name',
            'datasets.actions': 'Actions',
            'datasets.deleteTitle': 'Delete Dataset',
            'datasets.deleteMessage':
              'Are you sure you want to delete the dataset "{name}"? This action cannot be undone.',
            'datasets.enterName': 'Enter the name of the new dataset:',
            'datasets.nameRequired': 'Dataset name is required.',
            'settings.title': 'Settings',
            'settings.hfToken': 'Hugging Face Token',
            'settings.hfHelp': 'To access gated/private models, create a Read token:',
            'settings.hfPlaceholder': 'Enter your Hugging Face token',
            'settings.trainingPath': 'Training Folder Path',
            'settings.trainingHelp':
              'We will store your training information here. Must be an absolute path. If blank, it will default to the output folder in the project root.',
            'settings.trainingPlaceholder': 'Enter training folder path',
            'settings.datasetPath': 'Dataset Folder Path',
            'settings.datasetHelp': 'Where we store and find your datasets.',
            'settings.datasetWarning':
              'Warning: This software may modify datasets, so keep a backup or use a dedicated folder.',
            'settings.datasetPlaceholder': 'Enter datasets folder path',
            'settings.saving': 'Saving...',
            'settings.save': 'Save Settings',
            'settings.saved': 'Settings saved successfully!',
            'settings.error': 'Error saving settings. Please try again.',
            'common.actions': 'Actions',
            'common.cancel': 'Cancel',
            'common.confirm': 'Confirm',
            'common.create': 'Create',
            'common.delete': 'Delete',
            'common.refresh': 'Refresh',
            'common.empty': 'Empty',
            'common.loading': 'Loading...',
            'jobs.name': 'Name',
            'jobs.steps': 'Steps',
            'jobs.status': 'Status',
            'jobs.info': 'Info',
            'jobs.idle': 'Idle',
            'jobs.running': 'Queue Running',
            'jobs.stopped': 'Queue Stopped',
            'jobs.start': 'START',
            'jobs.stop': 'STOP',
            'jobs.clear': 'Clear',
            'jobs.deleteSelected': 'Delete Selected',
            'jobs.selected': '{count} jobs selected',
            'jobs.deleting': 'Deleting {done} / {total}...',
            'jobs.deleteTitle': 'Delete Jobs',
            'jobs.deleteMessage':
              'Are you sure you want to delete {count} jobs? This will also permanently remove them from your disk.',
            'jobs.status.queued': 'Queued',
            'jobs.status.running': 'Running',
            'jobs.status.stopping': 'Stopping',
            'jobs.status.completed': 'Completed',
            'jobs.status.failed': 'Failed',
            'gpu.temperature': 'Temperature',
            'gpu.fanSpeed': 'Fan Speed',
            'gpu.load': 'GPU Load',
            'gpu.memory': 'Memory',
            'gpu.clockSpeed': 'Clock Speed',
            'gpu.powerDraw': 'Power Draw',
            'gpu.noData': 'No GPU data available.',
            'gpu.noNvidia': 'No NVIDIA GPUs detected!',
            'gpu.noNvidiaHelp': 'nvidia-smi is not available on this system.',
            'gpu.noneFound': 'No GPUs found, but nvidia-smi is available.',
            'gpu.error': 'Error!',
            'auth.password': 'Password',
            'auth.placeholder': 'Enter your password',
            'auth.help': 'The password is set with AI_TOOLKIT_AUTH; the default is "password".',
            'auth.checking': 'Checking...',
            'auth.check': 'Check Password',
            'auth.invalid': 'Invalid token. Please try again.',
            'auth.required': 'Please enter your token',
            'newJob.title': 'New Training Job',
            'newJob.editTitle': 'Edit Training Job',
            'newJob.import': 'Import Config',
            'newJob.simple': 'Simple',
            'newJob.advanced': 'Advanced',
            'newJob.showSimple': 'Show Simple',
            'newJob.showAdvanced': 'Show Advanced',
            'newJob.saving': 'Saving...',
            'newJob.update': 'Update',
            'newJob.create': 'Create',
            'newJob.updateJob': 'Update Job',
            'newJob.createJob': 'Create Job',
            'newJob.advancedDetected': 'Advanced job detected. Please switch to advanced view to continue.',
          } satisfies Record<TranslationKey, string>;
          text = english[key];
        }
        return Object.entries(variables ?? {}).reduce(
          (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
          text,
        );
      },
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
